version: "3.8"

services:
  db:
    image: postgres:13
    container_name: linkedteam_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: linkedteam
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    container_name: linkedteam_web
    command: pipenv run flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://admin:admin123@db:5432/linkedteam # <--- ¡Aquí está el cambio!
      - FLASK_APP_KEY="any key works"
      # ... otras variables de entorno
    depends_on:
      - db

volumes:
  postgres_data:
