"""empty message

Revision ID: 056f79420001
Revises: fc24ca64a4f9
Create Date: 2023-02-13 16:09:14.357059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056f79420001'
down_revision = 'fc24ca64a4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint('cliente_estatus_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.create_unique_constraint('cliente_estatus_key', ['estatus'])

    # ### end Alembic commands ###
