"""empty message

Revision ID: 18957fb69df4
Revises: eedfd3f1806c
Create Date: 2023-05-19 13:50:07.808447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18957fb69df4'
down_revision = 'eedfd3f1806c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
