"""empty message

Revision ID: 25c5419cbab3
Revises: 2ded7a3ca276
Create Date: 2023-07-06 10:24:14.698864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c5419cbab3'
down_revision = '2ded7a3ca276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agency_ybt', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('own_agency', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('own_agency')
        batch_op.drop_column('agency_ybt')

    # ### end Alembic commands ###
