"""empty message

Revision ID: 2744905cc805
Revises: d2d8532d897a
Create Date: 2023-02-07 15:25:05.784944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2744905cc805'
down_revision = 'd2d8532d897a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('celular', sa.String(length=50), nullable=False),
    sa.Column('monto', sa.String(length=20), nullable=False),
    sa.Column('confianza', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celular')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cliente')
    # ### end Alembic commands ###
