"""empty message

Revision ID: 502925c7c7c9
Revises: a6a951485ac4
Create Date: 2024-02-23 17:27:42.283389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502925c7c7c9'
down_revision = 'a6a951485ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client__policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('policy_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('policy_type', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('client__policies_policy_id_fkey', type_='foreignkey')
        batch_op.drop_column('date_notes')
        batch_op.drop_column('policy_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client__policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('policy_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_notes', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('client__policies_policy_id_fkey', 'policies_names', ['policy_id'], ['id'])
        batch_op.drop_column('policy_type')
        batch_op.drop_column('policy_name')

    # ### end Alembic commands ###
