"""empty message

Revision ID: 75191fad69b1
Revises: c9312cbbc8a8
Create Date: 2023-02-10 16:39:20.561918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75191fad69b1'
down_revision = 'c9312cbbc8a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
