"""empty message

Revision ID: a6a951485ac4
Revises: 3060b7e2be9c
Create Date: 2024-02-23 16:13:49.207697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a951485ac4'
down_revision = '3060b7e2be9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('policies_names', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agencies_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'agencies', ['agencies_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policies_names', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('agencies_id')

    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
