"""empty message

Revision ID: bbaa4ef56d5b
Revises: 704c655722c4
Create Date: 2023-05-22 13:06:17.546738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbaa4ef56d5b'
down_revision = '704c655722c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarea', sa.String(length=250), nullable=False),
    sa.Column('estatus', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('admin', 'manager', 'associated', name='role'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('admin', 'manager', 'associated', name='role'),
               nullable=True)

    op.drop_table('tarea')
    # ### end Alembic commands ###
