"""empty message

Revision ID: bd2a7e8d6bdd
Revises: 7dc7eb5fde40
Create Date: 2023-08-02 16:20:46.067010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd2a7e8d6bdd'
down_revision = '7dc7eb5fde40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
