"""empty message

Revision ID: beaa63be18cb
Revises: eed6d85adcae
Create Date: 2024-03-20 14:45:13.774200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beaa63be18cb'
down_revision = 'eed6d85adcae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('courses_manager_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_unique_constraint('courses_manager_id_key', ['manager_id'])

    # ### end Alembic commands ###
