"""empty message

Revision ID: c048138e3fd7
Revises: 0d199a304335
Create Date: 2024-05-01 18:46:00.667365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c048138e3fd7'
down_revision = '0d199a304335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('business_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
