"""empty message

Revision ID: c9312cbbc8a8
Revises: 2744905cc805
Create Date: 2023-02-10 16:08:30.777784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9312cbbc8a8'
down_revision = '2744905cc805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
