"""empty message

Revision ID: cb8cbf194203
Revises: 94b3d2f0cf26
Create Date: 2023-08-01 10:11:21.947741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8cbf194203'
down_revision = '94b3d2f0cf26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.drop_column('agency_logo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agency_logo', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
