"""empty message

Revision ID: e1b579d6451e
Revises: a9212508e2b8
Create Date: 2023-05-16 11:27:11.218593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b579d6451e'
down_revision = 'a9212508e2b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('agency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agency', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
