"""empty message

Revision ID: f2fa4c0200c7
Revises: fce2814bff98
Create Date: 2023-10-02 12:50:02.469258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2fa4c0200c7'
down_revision = 'fce2814bff98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint('cliente_cellphone_key', type_='unique')
        batch_op.drop_constraint('cliente_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.create_unique_constraint('cliente_email_key', ['email'])
        batch_op.create_unique_constraint('cliente_cellphone_key', ['cellphone'])

    # ### end Alembic commands ###
