"""empty message

Revision ID: fce2814bff98
Revises: 7705033dc431
Create Date: 2023-10-02 11:59:58.374693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce2814bff98'
down_revision = '7705033dc431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('cellphone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('cellphone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
